//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacCred.Screens {
    
    
    public partial class AdminScreen {
        
        /// <summary>
        /// mainMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FacCred.Screens.MainMenu mainMenu;
        
        /// <summary>
        /// Subheader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.Subheader Subheader1;
        
        /// <summary>
        /// txt_sessionUserLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label txt_sessionUserLevel;
        
        /// <summary>
        /// notes_btn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton notes_btn;
        
        /// <summary>
        /// archive_btn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton archive_btn;
        
        /// <summary>
        /// Globalizedbutton5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton Globalizedbutton5;
        
        /// <summary>
        /// coursesBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton coursesBtn;
        
        /// <summary>
        /// Globalizedbutton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton Globalizedbutton1;
        
        /// <summary>
        /// Globalizedbutton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton Globalizedbutton4;
        
        /// <summary>
        /// Globalizedbutton6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton Globalizedbutton6;
        
        /// <summary>
        /// Globalizedbutton7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton Globalizedbutton7;
        
        /// <summary>
        /// Globalizedbutton8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jenzabar.Common.Web.UI.Controls.GlobalizedButton Globalizedbutton8;
    }
}
